import { Link } from 'react-router-dom';
import { ArrowRight } from 'lucide-react';

export default function InfoSection() {
  return (
    <section className="bg-[#F5F5F5] px-4 sm:px-6 py-16 sm:py-24">
      <div className="max-w-[88rem] mx-auto">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 sm:gap-12 mb-12 sm:mb-16 items-start">
          <div>
            <h2 className="text-black text-4xl md:text-5xl font-medium leading-tight mb-8" style={{ letterSpacing: '-0.03em' }}>
              Meet sXLM.
            </h2>
            <Link
              to="/docs"
              className="inline-flex items-center gap-3 bg-black text-white text-base font-medium pl-8 pr-2 py-2 rounded-full hover:bg-gray-800 transition-colors duration-200"
              style={{ textDecoration: 'none' }}
            >
              Read the Docs
              <span className="bg-white rounded-full p-2 flex items-center justify-center">
                <ArrowRight className="w-4 h-4 text-black" />
              </span>
            </Link>
          </div>
          <div>
            <p className="text-black/70 text-xl sm:text-2xl md:text-3xl leading-relaxed">
              sXLM is a vault share token representing a proportional claim on pooled XLM
              and any net yield generated by approved Stellar DeFi strategies.
            </p>
          </div>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {/* Card 1 — image bg, spans 2 cols */}
          <div
            className="lg:col-span-2 rounded-2xl min-h-80 flex flex-col justify-between p-7 overflow-hidden"
            style={{
              backgroundImage: `url('https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260423_164207_f243351d-ed59-48ec-83a0-a5e996bdbe3c.png&w=1280&q=85')`,
              backgroundSize: 'cover',
              backgroundPosition: 'center',
            }}
          >
            <p className="text-black text-2xl font-medium leading-snug" style={{ letterSpacing: '-0.02em' }}>
              Yield that<br />compounds
            </p>
            <p className="text-black/70 text-base max-w-xs">
              As approved strategies generate real net revenue, the vault exchange rate rises ,
              your sXLM is worth more XLM over time.
            </p>
          </div>

          {/* Card 2 — dark purple */}
          <div className="rounded-2xl min-h-80 flex flex-col justify-between p-7" style={{ background: '#2B2644' }}>
            <p className="text-white text-2xl font-medium leading-snug" style={{ letterSpacing: '-0.02em' }}>
              Non-custodial<br />& composable.
            </p>
            <p className="text-white/60 text-base">
              sXLM is a composable vault share token. Use it across Stellar DeFi — as collateral,
              in AMM pools, or for governance.
            </p>
          </div>

          {/* Card 3 — dark purple */}
          <div className="rounded-2xl min-h-80 flex flex-col justify-between p-7" style={{ background: '#2B2644' }}>
            <p className="text-white text-2xl font-medium leading-snug" style={{ letterSpacing: '-0.02em' }}>
              Fully<br />transparent.
            </p>
            <p className="text-white/60 text-base">
              Strategy performance, exchange rate history, and risk metrics are reported openly.
              APY reflects realized net revenue, not a guarantee.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
