import { useState, useEffect } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { Hash } from 'lucide-react';

/* ── Types ── */
interface SidebarGroup {
  label: string;
  items: { id: string; title: string }[];
}

/* ── Sidebar structure ── */
const SIDEBAR_GROUPS: SidebarGroup[] = [
  {
    label: 'Start',
    items: [
      { id: 'welcome', title: 'Welcome to StelloFi' },
      { id: 'mission', title: 'Our Mission' },
      { id: 'architecture', title: 'Architecture Overview' },
    ],
  },
  {
    label: 'Core Concepts',
    items: [
      { id: 'sxlm-token', title: 'What is sXLM' },
      { id: 'exchange-rate', title: 'Exchange Rate Model' },
      { id: 'minting-redemption', title: 'Minting & Redemption' },
      { id: 'yield-sources', title: 'Yield Sources' },
    ],
  },
  {
    label: 'Protocol',
    items: [
      { id: 'vault', title: 'Vault Contract' },
      { id: 'lending', title: 'Lending' },
      { id: 'amm-pool', title: 'AMM Pool' },
      { id: 'governance-docs', title: 'Governance' },
    ],
  },
  {
    label: 'Risk & Security',
    items: [
      { id: 'risk-management', title: 'Risk Management' },
      { id: 'liquidity-model', title: 'Liquidity Model' },
      { id: 'insurance-fund', title: 'Insurance Fund' },
      { id: 'audit-plan', title: 'Audit Plan' },
    ],
  },
  {
    label: 'Developers',
    items: [
      { id: 'contracts', title: 'Contract Addresses' },
      { id: 'getting-started-dev', title: 'Getting Started' },
    ],
  },
];

/* ── Anchor heading component ── */
function H2({ id, children }: { id: string; children: React.ReactNode }) {
  return (
    <h2 id={id} className="group flex items-center gap-2 text-2xl font-medium text-black mt-12 mb-4 scroll-mt-20" style={{ letterSpacing: '-0.03em' }}>
      {children}
      <a href={`#${id}`} className="opacity-0 group-hover:opacity-40 transition-opacity">
        <Hash className="w-4 h-4" />
      </a>
    </h2>
  );
}

function H3({ id, children }: { id: string; children: React.ReactNode }) {
  return (
    <h3 id={id} className="group flex items-center gap-2 text-lg font-medium text-black mt-8 mb-3 scroll-mt-20" style={{ letterSpacing: '-0.02em' }}>
      {children}
      <a href={`#${id}`} className="opacity-0 group-hover:opacity-40 transition-opacity">
        <Hash className="w-3.5 h-3.5" />
      </a>
    </h3>
  );
}

function P({ children }: { children: React.ReactNode }) {
  return <p className="text-black/70 text-base leading-relaxed mb-4">{children}</p>;
}

function Code({ children }: { children: React.ReactNode }) {
  return <code className="font-mono text-sm bg-[#F5F5F5] px-1.5 py-0.5 rounded text-black border border-[#e5e5e5]">{children}</code>;
}

function Formula({ children }: { children: React.ReactNode }) {
  return (
    <div className="bg-[#F5F5F5] border border-[#e5e5e5] rounded-xl px-6 py-4 my-4 font-mono text-sm text-black">
      {children}
    </div>
  );
}

function InfoCard({ title, desc, tag }: { title: string; desc: string; tag?: string }) {
  return (
    <div className="card p-5 flex flex-col gap-2">
      {tag && <span className="text-xs text-black/40 uppercase tracking-wider">{tag}</span>}
      <p className="font-medium text-black text-sm">{title}</p>
      <p className="text-xs text-black/60 leading-relaxed">{desc}</p>
    </div>
  );
}

/* ── Doc content ── */
function DocContent() {
  return (
    <div className="prose-custom max-w-none">

      {/* ── WELCOME ── */}
      <section id="welcome" className="scroll-mt-20">
        <div className="mb-6">
          <p className="text-sm text-black/50 mb-2">Start</p>
          <h1 className="text-4xl font-medium text-black mb-2" style={{ letterSpacing: '-0.04em' }}>Welcome to StelloFi</h1>
          <p className="text-black/60 text-lg">A yield-bearing XLM vault built on Stellar Soroban.</p>
        </div>

        <P>
          StelloFi is a yield-bearing XLM vault that accepts XLM deposits and issues <strong className="text-black font-medium">sXLM</strong> — a vault share token
          representing a proportional claim on pooled XLM and any net yield generated by approved Stellar DeFi strategies.
        </P>
        <P>
          The core thesis is that sXLM is a composable vault share token backed by pooled XLM and conservative Stellar DeFi strategies.
          Its value increases only if the underlying vault strategies generate real net revenue after fees, losses, liquidity buffers, and risk reserves.
        </P>

        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 my-8">
          <InfoCard tag="Base Layer" title="Stellar Network" desc="Built on Stellar Soroban — Rust smart contracts compiled to WebAssembly." />
          <InfoCard tag="Collateral" title="Native XLM" desc="Deposit native XLM to receive sXLM vault share tokens proportionally." />
          <InfoCard tag="Yield" title="DeFi Strategies" desc="Yield from approved lending markets, AMM fees, and protocol incentives." />
        </div>

        <H2 id="get-started">Get started</H2>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 my-6">
          <Link to="/stake" className="card p-5 hover:shadow-md transition-shadow" style={{ textDecoration: 'none' }}>
            <p className="font-medium text-black mb-2">Stake XLM →</p>
            <p className="text-sm text-black/60">Deposit XLM and receive sXLM vault share tokens. Your share of the vault grows as strategies generate revenue.</p>
          </Link>
          <Link to="/docs#architecture" className="card p-5 hover:shadow-md transition-shadow" style={{ textDecoration: 'none' }}>
            <p className="font-medium text-black mb-2">Read the Architecture →</p>
            <p className="text-sm text-black/60">Understand the three-layer architecture: Soroban contracts, off-chain engines, and the React client.</p>
          </Link>
        </div>
      </section>

      <div className="border-t border-[#e5e5e5] my-12" />

      {/* ── MISSION ── */}
      <section id="mission" className="scroll-mt-20">
        <H2 id="mission-h">Our Mission</H2>
        <P>
          StelloFi exists to make XLM productive. Rather than sitting idle in a wallet, XLM deposited into the StelloFi vault
          is routed through conservative, governance-approved DeFi strategies on Stellar — generating real net revenue
          that accrues proportionally to all vault shareholders via the rising exchange rate.
        </P>
        <P>
          The protocol prioritizes <strong className="text-black font-medium">safety, liquidity, and transparent reporting</strong> over high APY targets.
          During early deployment, expected organic yield may be low. That is intentional — capital preservation
          and trustworthy infrastructure come first.
        </P>

        <H3 id="principles">Core Principles</H3>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 my-4">
          {[
            { title: 'Non-custodial', desc: 'Users retain cryptographic control via Stellar Freighter. The protocol never holds signing authority.' },
            { title: 'Transparent', desc: 'Strategy performance, exchange rate history, and risk metrics are reported openly on-chain and via the analytics dashboard.' },
            { title: 'Conservative', desc: 'New strategies require governance approval, audits, allocation caps, and risk scoring before receiving vault funds.' },
            { title: 'Composable', desc: 'sXLM is usable across Stellar DeFi — as collateral in lending markets, in AMM pools, and for governance participation.' },
          ].map((p) => (
            <div key={p.title} className="bg-[#F5F5F5] rounded-xl p-4 border border-[#e5e5e5]">
              <p className="font-medium text-black text-sm mb-1">{p.title}</p>
              <p className="text-xs text-black/60 leading-relaxed">{p.desc}</p>
            </div>
          ))}
        </div>
      </section>

      <div className="border-t border-[#e5e5e5] my-12" />

      {/* ── ARCHITECTURE ── */}
      <section id="architecture" className="scroll-mt-20">
        <H2 id="architecture-h">Architecture Overview</H2>
        <P>
          StelloFi is orchestrated across three distinct but deeply integrated operational layers:
          the on-chain Soroban execution environment, the off-chain algorithmic backend, and the user-facing client application.
        </P>

        <H3 id="soroban-contracts">Soroban Smart Contracts</H3>
        <P>
          The foundational logic of StelloFi is executed via five core Rust smart contracts deployed to the Stellar network.
          Each contract operates within the strict resource footprint constraints of the Soroban environment, compiled to WebAssembly.
        </P>
        <div className="overflow-x-auto my-4">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-[#e5e5e5]">
                <th className="text-left py-3 px-4 text-xs text-black/40 uppercase tracking-wider font-medium">Contract</th>
                <th className="text-left py-3 px-4 text-xs text-black/40 uppercase tracking-wider font-medium">Address (Mainnet)</th>
                <th className="text-left py-3 px-4 text-xs text-black/40 uppercase tracking-wider font-medium">Purpose</th>
              </tr>
            </thead>
            <tbody>
              {[
                { name: 'sxlm-token', addr: 'CAS3...OWMA', desc: 'Vault share token — share accounting, minting, burning' },
                { name: 'vault', addr: 'CDYX...45PS', desc: 'Primary entry point — receives XLM, routes to strategies' },
                { name: 'lending', addr: 'CAOW...QNJG', desc: 'Overcollateralized borrowing and lending engine' },
                { name: 'lp-pool', addr: 'CAW2...VLHV', desc: 'AMM for XLM/sXLM liquidity' },
                { name: 'governance', addr: 'CB7L...DEP4', desc: 'Timelock proposals, quorum, strategy approvals' },
              ].map((c) => (
                <tr key={c.name} className="border-b border-[#e5e5e5] hover:bg-[#F5F5F5] transition-colors">
                  <td className="py-3 px-4 font-mono text-xs text-black">{c.name}</td>
                  <td className="py-3 px-4 font-mono text-xs text-black/50">{c.addr}</td>
                  <td className="py-3 px-4 text-xs text-black/70">{c.desc}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <H3 id="off-chain">Off-Chain Infrastructure</H3>
        <P>
          Because on-chain smart contracts cannot natively schedule execution or efficiently solve complex allocation problems,
          StelloFi relies on off-chain services for indexing, analytics, reporting, and keeper coordination.
          These services do not define user balances or the vault exchange rate — those accounting rules remain enforced by Soroban contracts.
        </P>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 my-4">
          {[
            { name: 'Risk Engine', desc: 'Continuously evaluates collateralization, liquidity depth, strategy exposure, oracle status, and withdrawal pressure.' },
            { name: 'Strategy Allocation Engine', desc: 'Proposes rebalances across approved strategies within governance-approved allocation caps.' },
            { name: 'Keeper Service', desc: 'Executes keeper tasks with limited permissions — cannot arbitrarily move user funds.' },
            { name: 'Event Bus', desc: 'Processes on-chain events from Stellar Horizon for real-time analytics and state indexing.' },
          ].map((s) => (
            <div key={s.name} className="bg-[#F5F5F5] rounded-xl p-4 border border-[#e5e5e5]">
              <p className="font-medium text-black text-sm mb-1">{s.name}</p>
              <p className="text-xs text-black/60 leading-relaxed">{s.desc}</p>
            </div>
          ))}
        </div>
      </section>

      <div className="border-t border-[#e5e5e5] my-12" />

      {/* ── SXLM TOKEN ── */}
      <section id="sxlm-token" className="scroll-mt-20">
        <p className="text-sm text-black/50 mb-2">Core Concepts</p>
        <H2 id="sxlm-h">What is sXLM</H2>
        <P>
          sXLM is the vault share token of the StelloFi protocol. It is not a stablecoin. It is closer to a vault receipt token
          or yield-bearing wrapper — a tokenized claim on a proportional share of all XLM held and managed by the vault.
        </P>
        <P>
          Within the Soroban <Code>sxlm-token</Code> smart contract, user balances are not stored as absolute quantities of sXLM.
          Instead, the contract records the number of <strong className="text-black font-medium">abstract shares</strong> owned by each user.
          The XLM value of these shares fluctuates with the total pooled XLM managed by the protocol.
        </P>
        <Formula>
          {'B_u(t) = S_u(t) × E(t)'}
          <br />
          {'where S_u(t) = shares held by user u, E(t) = exchange rate at time t'}
        </Formula>
      </section>

      <div className="border-t border-[#e5e5e5] my-12" />

      {/* ── EXCHANGE RATE ── */}
      <section id="exchange-rate" className="scroll-mt-20">
        <H2 id="er-h">Exchange Rate Model</H2>
        <P>
          The Core Exchange Rate <Code>E(t)</Code> defines the exact amount of native XLM equivalent to a single unit of sXLM at any moment.
          It is calculated as the ratio of total pooled assets to the total supply of shares:
        </P>
        <Formula>
          {'E(t) = T_XLM(t) / S_total(t)'}
          <br />
          {'where T_XLM(t) = total pooled XLM, S_total(t) = total circulating shares'}
        </Formula>
        <P>
          When approved strategies generate real net revenue — such as lending interest or liquidity incentives that exceed associated costs —
          <Code>T_XLM(t)</Code> increases while <Code>S_total(t)</Code> remains static. Consequently, <Code>E(t)</Code> increases over time,
          assuming no strategy loss, bad debt, or reserve drawdown.
        </P>
        <P>
          The sXLM exchange rate is <strong className="text-black font-medium">not set by an oracle</strong>. It is computed from vault assets and total shares.
          Oracles are used only for external asset pricing, collateral valuation, and liquidation logic.
        </P>

        <H3 id="wad-ray">Fixed-Point Arithmetic (Wad/Ray)</H3>
        <P>
          The Soroban WebAssembly runtime lacks native floating-point arithmetic. To prevent truncation errors compounding across millions of transactions,
          StelloFi implements fixed-point arithmetic using Wad and Ray scaling mechanics:
        </P>
        <Formula>
          {'Wad = 10^18  (standard precision)'}
          <br />
          {'Ray = 10^27  (high-precision temporal indexing)'}
          <br />
          {'All calculations use Soroban native i128 (128-bit integer) to prevent overflow.'}
        </Formula>
      </section>

      <div className="border-t border-[#e5e5e5] my-12" />

      {/* ── MINTING & REDEMPTION ── */}
      <section id="minting-redemption" className="scroll-mt-20">
        <H2 id="mint-h">Minting & Redemption</H2>
        <P>
          When a user deposits <Code>ΔX</Code> XLM into the vault at time <Code>t</Code>, the protocol calculates the exact number of shares <Code>ΔS</Code> to mint:
        </P>
        <Formula>
          {'ΔS = ΔX / E(t)'}
          <br />
          {'After deposit: S_total(t⁺) = S_total(t) + ΔS, T_XLM(t⁺) = T_XLM(t) + ΔX'}
          <br />
          {'Exchange rate preserved: E(t⁺) = E(t) ✓'}
        </Formula>
        <P>
          Conversely, upon withdrawal for <Code>ΔX</Code> XLM, the shares targeted for destruction use the exact same formula.
          Burning shares decreases both total share supply and total pooled XLM symmetrically — preserving the integrity of <Code>E(t)</Code> across all operations.
        </P>

        <H3 id="secondary-market">Secondary Market vs Vault Rate</H3>
        <P>
          Secondary market price may deviate from <Code>E(t)</Code> because of liquidity, withdrawal delays, risk perception, or market stress.
          StelloFi monitors discount or premium to exchange rate, pool liquidity depth, redemption queue duration, oracle deviation, and withdrawal buffer coverage.
        </P>
      </section>

      <div className="border-t border-[#e5e5e5] my-12" />

      {/* ── YIELD SOURCES ── */}
      <section id="yield-sources" className="scroll-mt-20">
        <H2 id="yield-h">Yield Sources</H2>
        <P>
          StelloFi does not assume native Stellar staking rewards — <strong className="text-black font-medium">Stellar has no native staking yield or validator slashing mechanism</strong>.
          Yield is generated only when external strategies produce real revenue. The initial strategy set is conservative and limited to:
        </P>
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 my-4">
          {[
            { title: 'Blend Lending Markets', desc: 'XLM supplied to Stellar lending markets where utilization and risk parameters justify deployment.' },
            { title: 'DEX / AMM Fees', desc: 'XLM or sXLM liquidity deployed only when expected fees exceed impermanent loss, slippage, and withdrawal costs.' },
            { title: 'Protocol Incentives', desc: 'A portion of protocol fees or ecosystem incentives directed to bootstrap sXLM liquidity.' },
          ].map((s) => (
            <div key={s.title} className="card p-4">
              <p className="font-medium text-black text-sm mb-2">{s.title}</p>
              <p className="text-xs text-black/60 leading-relaxed">{s.desc}</p>
            </div>
          ))}
        </div>
        <P>
          Vault APY displayed to users is derived from changes in the vault exchange rate over an observation period.
          The frontend labels APY as an estimate based on realized net strategy performance, not as a guaranteed return.
        </P>
      </section>

      <div className="border-t border-[#e5e5e5] my-12" />

      {/* ── VAULT ── */}
      <section id="vault" className="scroll-mt-20">
        <p className="text-sm text-black/50 mb-2">Protocol</p>
        <H2 id="vault-h">Vault Contract</H2>
        <P>
          The <Code>vault</Code> contract is the primary entry point for user interaction. It receives native XLM deposits,
          triggers sXLM minting, custodies the liquidity buffer, and routes capital only to governance-approved strategies within allocation caps.
        </P>
        <P>
          Strategy allocation is governed by deterministic risk constraints. Each strategy receives an allocation cap based on
          smart contract risk, liquidity risk, oracle risk, historical utilization, withdrawal delay, counterparty exposure,
          audit status, and maximum loss estimate.
        </P>
        <Formula>
          {'Each strategy i has allocation weight w_i'}
          <br />
          {'Keeper may rebalance only within governance-approved caps'}
          <br />
          {'Breaching strategy limits requires multisig governance approval'}
        </Formula>
      </section>

      <div className="border-t border-[#e5e5e5] my-12" />

      {/* ── LENDING ── */}
      <section id="lending" className="scroll-mt-20">
        <H2 id="lending-h">Lending</H2>
        <P>
          The <Code>lending</Code> contract supports overcollateralized borrowing. Every supported collateral asset is parameterized by governance:
        </P>
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 my-4">
          {[
            { name: 'Base LTV', desc: 'Maximum borrowing power granted per unit of collateral.' },
            { name: 'Liquidation Threshold', desc: 'Point at which a position is flagged as undercollateralized and subject to liquidation.' },
            { name: 'Liquidation Penalty', desc: 'Fee extracted during liquidation to incentivize liquidators or keeper services.' },
          ].map((p) => (
            <div key={p.name} className="bg-[#F5F5F5] rounded-xl p-4 border border-[#e5e5e5]">
              <p className="font-medium text-black text-sm mb-1">{p.name}</p>
              <p className="text-xs text-black/60">{p.desc}</p>
            </div>
          ))}
        </div>
        <Formula>
          {'Health Factor (HF) = Σ(collateral_i × LT_i) / total_borrowed'}
          <br />
          {'HF < 1.0 → position eligible for liquidation'}
        </Formula>
        <P>
          Recursive leverage using sXLM as collateral is treated as a user-level leveraged position,
          not protocol-level organic yield. The protocol caps recursive exposure and applies conservative LTVs
          to prevent circular accounting where borrowed XLM is redeposited to inflate TVL or displayed APY.
        </P>
      </section>

      <div className="border-t border-[#e5e5e5] my-12" />

      {/* ── AMM POOL ── */}
      <section id="amm-pool" className="scroll-mt-20">
        <H2 id="amm-h">AMM Pool</H2>
        <P>
          The <Code>lp-pool</Code> contract implements a constant-product AMM for XLM/sXLM liquidity.
          The pool should <strong className="text-black font-medium">not assume a permanent 1:1 peg</strong> — since sXLM represents a claim on vault assets,
          its fair value is determined by the current exchange rate <Code>E(t)</Code>.
        </P>
        <P>
          If 1 sXLM is redeemable for 1.03 XLM, the pool treats 1.03 XLM as the reference price, not 1.00 XLM.
          Any stable-swap or concentrated-liquidity design must account for this drifting exchange rate,
          otherwise arbitrageurs may extract value from LPs or the pool may misprice sXLM during yield accrual.
        </P>
      </section>

      <div className="border-t border-[#e5e5e5] my-12" />

      {/* ── GOVERNANCE ── */}
      <section id="governance-docs" className="scroll-mt-20">
        <H2 id="gov-h">Governance</H2>
        <P>
          The <Code>governance</Code> contract facilitates decentralized parameter configuration with timelock execution.
          Parameters subject to governance include protocol fees, collateral risk factors, oracle providers,
          strategy approvals, liquidity-buffer targets, and allocation caps.
        </P>
        <P>
          The keeper operates as a limited-permission role controlled by multisig and constrained by on-chain policy.
          It cannot arbitrarily move user funds — it can only call predefined contract functions and route funds
          to governance-approved strategies within allocation caps.
        </P>
      </section>

      <div className="border-t border-[#e5e5e5] my-12" />

      {/* ── RISK MANAGEMENT ── */}
      <section id="risk-management" className="scroll-mt-20">
        <p className="text-sm text-black/50 mb-2">Risk & Security</p>
        <H2 id="risk-h">Risk Management</H2>
        <P>
          StelloFi does not face validator slashing — Stellar has no native staking yield or validator slashing mechanism.
          The relevant vault risks are strategy loss, bad debt, oracle failure, exploit loss, and liquidity shortfall.
        </P>
        <P>
          If an integrated strategy suffers an irrecoverable loss <Code>L_event</Code>, total XLM-equivalent vault assets are reduced.
          Because total shares remain unchanged, the vault exchange rate <Code>E(t)</Code> decreases and the loss is reflected
          transparently in assets per share.
        </P>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 my-4">
          {[
            { risk: 'Strategy Loss', mitigation: 'Allocation caps, governance approval, audit requirements before deployment.' },
            { risk: 'Bad Debt', mitigation: 'Conservative LTV ratios, liquidation thresholds, and insurance fund absorption.' },
            { risk: 'Oracle Failure', mitigation: 'TWAP prices, stale price rejection, fallback oracle routes, circuit breakers.' },
            { risk: 'Liquidity Shortfall', mitigation: 'Dynamic buffer ratio, withdrawal queue, scenario-based liquidity modeling.' },
          ].map((r) => (
            <div key={r.risk} className="card p-4">
              <p className="font-medium text-black text-sm mb-1">{r.risk}</p>
              <p className="text-xs text-black/60 leading-relaxed">{r.mitigation}</p>
            </div>
          ))}
        </div>
      </section>

      <div className="border-t border-[#e5e5e5] my-12" />

      {/* ── LIQUIDITY MODEL ── */}
      <section id="liquidity-model" className="scroll-mt-20">
        <H2 id="liq-h">Liquidity Model</H2>
        <P>
          The vault maintains a liquidity buffer — a target ratio <Code>β_target</Code> of TVL — dynamically adjusted based on
          observed withdrawals, strategy liquidity, and market stress.
        </P>
        <P>
          If idle liquidity is sufficient, withdrawals settle directly from the buffer. If requested withdrawals exceed
          available buffer liquidity, users enter a redemption queue while the keeper repatriates funds from approved strategies.
          Displayed withdrawal estimates are labeled as estimates, not guarantees.
        </P>

        <H3 id="depeg">Depeg Handling</H3>
        <P>
          sXLM may trade below its vault exchange rate during liquidity stress, oracle uncertainty, or strategy risk.
          A depeg does not automatically mean insolvency — the key distinction is whether market price deviated from vault exchange rate
          due to temporary liquidity stress or because underlying vault assets suffered losses.
        </P>
      </section>

      <div className="border-t border-[#e5e5e5] my-12" />

      {/* ── INSURANCE FUND ── */}
      <section id="insurance-fund" className="scroll-mt-20">
        <H2 id="ins-h">Insurance Fund</H2>
        <P>
          The insurance fund is funded through a defined portion of protocol fees. Its purpose is to absorb limited losses
          from bad debt, oracle failures, or approved strategy losses. It should not be marketed as a guarantee of full repayment.
        </P>
        <P>
          The fund reduces loss severity but does not eliminate strategy risk. If losses exceed the fund,
          remaining losses are socialized through a lower vault exchange rate.
        </P>
      </section>

      <div className="border-t border-[#e5e5e5] my-12" />

      {/* ── AUDIT PLAN ── */}
      <section id="audit-plan" className="scroll-mt-20">
        <H2 id="audit-h">Audit Plan</H2>
        <P>Before mainnet deployment, StelloFi completes:</P>
        <ul className="space-y-2 my-4 text-sm text-black/70">
          {[
            'Internal unit and integration testing',
            'Property-based testing for share accounting',
            'Invariant testing for deposits, withdrawals, and exchange-rate updates',
            'External audit of Soroban contracts',
            'Oracle manipulation review',
            'Keeper permission review',
            'Economic stress testing',
            'Public bug bounty after audit fixes',
          ].map((item) => (
            <li key={item} className="flex items-start gap-2">
              <span className="text-black mt-0.5">—</span>
              <span>{item}</span>
            </li>
          ))}
        </ul>

        <H3 id="invariants">Critical Invariants</H3>
        <div className="space-y-2 my-4">
          {[
            'User deposits must not dilute existing users',
            'Withdrawals must burn correct shares',
            'Exchange rate cannot be arbitrarily changed by admin',
            'Keeper cannot drain funds',
            'Strategy losses must be reflected transparently',
            'Total assets ≥ redeemable liabilities unless a loss event is declared',
          ].map((inv) => (
            <div key={inv} className="flex items-start gap-2 text-sm">
              <span className="text-green-600 font-mono mt-0.5">✓</span>
              <span className="text-black/70">{inv}</span>
            </div>
          ))}
        </div>
      </section>

      <div className="border-t border-[#e5e5e5] my-12" />

      {/* ── CONTRACT ADDRESSES ── */}
      <section id="contracts" className="scroll-mt-20">
        <p className="text-sm text-black/50 mb-2">Developers</p>
        <H2 id="contracts-h">Contract Addresses</H2>
        <P>All contracts deployed on Stellar Mainnet:</P>
        <div className="space-y-3 my-4">
          {[
            { name: 'sXLM Token', id: 'CAS3J7GYLGXMF6TDJBBYYSE3HQ6BBSMLNUQ34T6TZMYMW2EVH34XOWMA' },
            { name: 'Vault (Staking)', id: 'CDYXKWVDGEVA6OSIGN7GRAPPRN6AKID35OJL5ZZQIBCMECZ35KGL45PS' },
            { name: 'Lending', id: 'CAOWXZ6BWA2ZYY7GHD75OFKADKUJS4WCKPDYGGXULQWFJRB55TXAQNJG' },
            { name: 'LP Pool', id: 'CAW2DRMOI3CCJWKVMEUWYJUEQHXB4S4DR72HNL2DWQCMQQUH3LFFVLHV' },
            { name: 'Governance', id: 'CB7LV3FBQ7US26GVC7SM7RMX22IEEHAEUL7V3TDDWM32DHA5TDFDDEP4' },
          ].map((c) => (
            <div key={c.name} className="card p-4">
              <p className="text-xs text-black/50 mb-1">{c.name}</p>
              <p className="font-mono text-xs text-black break-all">{c.id}</p>
            </div>
          ))}
        </div>
      </section>

      <div className="border-t border-[#e5e5e5] my-12" />

      {/* ── GETTING STARTED (DEV) ── */}
      <section id="getting-started-dev" className="scroll-mt-20">
        <H2 id="dev-h">Getting Started</H2>
        <P>The StelloFi codebase is a monorepo with three components:</P>
        <div className="space-y-3 my-4">
          {[
            { path: 'frontend/', desc: 'React + Vite + TypeScript client app', detail: 'npm run dev (port 5173)' },
            { path: 'backend/', desc: 'Node.js + Fastify API + Prisma + Redis', detail: 'npm run dev (port 3001)' },
            { path: 'contract/', desc: 'Rust Soroban smart contracts (Cargo)', detail: 'cargo build --target wasm32-unknown-unknown' },
          ].map((p) => (
            <div key={p.path} className="card p-4">
              <p className="font-mono text-sm text-black mb-1">{p.path}</p>
              <p className="text-xs text-black/60 mb-1">{p.desc}</p>
              <p className="font-mono text-xs text-black/40">{p.detail}</p>
            </div>
          ))}
        </div>

        <H3 id="env-vars">Environment Variables</H3>
        <P>Frontend environment variables (prefix: <Code>VITE_</Code>):</P>
        <Formula>
          {'VITE_SXLM_TOKEN_CONTRACT_ID=CAS3...\nVITE_STAKING_CONTRACT_ID=CDYX...\nVITE_LENDING_CONTRACT_ID=CAOW...\nVITE_LP_POOL_CONTRACT_ID=CAW2...\nVITE_GOVERNANCE_CONTRACT_ID=CB7L...\nVITE_STELLAR_NETWORK=mainnet'}
        </Formula>
      </section>

    </div>
  );
}

/* ── Main Docs Page ── */
export default function Docs() {
  const [activeId, setActiveId] = useState('welcome');
  const location = useLocation();

  // All section ids to observe
  const allIds = SIDEBAR_GROUPS.flatMap(g => g.items.map(i => i.id));

  useEffect(() => {
    const observers: IntersectionObserver[] = [];
    allIds.forEach((id) => {
      const el = document.getElementById(id);
      if (!el) return;
      const obs = new IntersectionObserver(
        ([entry]) => { if (entry.isIntersecting) setActiveId(id); },
        { rootMargin: '-20% 0px -70% 0px' }
      );
      obs.observe(el);
      observers.push(obs);
    });
    return () => observers.forEach(o => o.disconnect());
  }, []);

  // Scroll to hash on load
  useEffect(() => {
    if (location.hash) {
      const el = document.getElementById(location.hash.slice(1));
      if (el) setTimeout(() => el.scrollIntoView({ behavior: 'smooth' }), 100);
    }
  }, [location.hash]);

  const scrollTo = (id: string) => {
    const el = document.getElementById(id);
    if (el) el.scrollIntoView({ behavior: 'smooth' });
  };

  // Find current group's items for right panel
  const activeGroup = SIDEBAR_GROUPS.find(g => g.items.some(i => i.id === activeId));

  return (
    <div className="flex h-[calc(100vh-60px)] bg-[#F5F5F5]">

      {/* ── Left sidebar ── */}
      <aside className="hidden md:flex flex-col w-56 xl:w-64 flex-shrink-0 border-r border-[#e5e5e5] bg-[#F5F5F5] overflow-y-auto">
        <div className="p-5 pt-6">
          {SIDEBAR_GROUPS.map((group) => (
            <div key={group.label} className="mb-5">
              <p className="text-xs font-semibold text-black/40 uppercase tracking-wider mb-2 px-2">{group.label}</p>
              <div className="space-y-0.5">
                {group.items.map((item) => {
                  const active = activeId === item.id;
                  return (
                    <button
                      key={item.id}
                      onClick={() => scrollTo(item.id)}
                      className="w-full text-left px-3 py-1.5 rounded-lg text-sm transition-colors duration-150"
                      style={{
                        color: active ? '#000' : '#6b7280',
                        background: active ? 'rgba(0,0,0,0.06)' : 'transparent',
                        fontWeight: active ? 500 : 400,
                      }}
                    >
                      {item.title}
                    </button>
                  );
                })}
              </div>
            </div>
          ))}
        </div>
      </aside>

      {/* ── Main content ── */}
      <main className="flex-1 overflow-y-auto">
        <div className="max-w-3xl mx-auto px-6 sm:px-10 py-10">
          <DocContent />
        </div>
      </main>

      {/* ── Right TOC ── */}
      <aside className="hidden xl:flex flex-col w-48 flex-shrink-0 border-l border-[#e5e5e5] bg-[#F5F5F5] overflow-y-auto">
        <div className="p-5 pt-6 sticky top-0">
          <p className="text-xs font-semibold text-black/40 uppercase tracking-wider mb-3 flex items-center gap-1">
            <span>≡</span> On this page
          </p>
          {activeGroup && (
            <div className="space-y-1">
              {activeGroup.items.map((item) => {
                const active = activeId === item.id;
                return (
                  <button
                    key={item.id}
                    onClick={() => scrollTo(item.id)}
                    className="w-full text-left text-xs py-1 transition-colors duration-150"
                    style={{ color: active ? '#000' : '#6b7280', fontWeight: active ? 500 : 400 }}
                  >
                    {item.title}
                  </button>
                );
              })}
            </div>
          )}
        </div>
      </aside>
    </div>
  );
}
